export const CREATE_PROJECT_DRAFT = 'CREATE_PROJECT_DRAFT'
export const ADD_PROJECT = 'ADD_PROJECT'
export const UPDATE_PROJECT_TITLE = 'UPDATE_PROJECT_TITLE'
export const DELETE_PROJECT = 'DELETE_PROJECT'

